### ISSUE TITLE
add guidelines.md and README.md for slates annotation

### ISSUE THREAD

**Issue by wricketts** [clamsproject/aapb-annotations#23]
### Because

The [january-slates](https://github.com/clamsproject/aapb-annotations/tree/main/january-slates) project contains an empty `guidelines.md` and an empty `README.md`. As stated in the [repository README](https://github.com/clamsproject/aapb-annotations/blob/main/README.md) file, we want each subdirectory to contain its own `README.md` detailing annotation project-specific information (e.g. project name, annotator demographics, annotation environment information, gold generation code dependencies, etc.). Each subdirectory should also contain a `guidelines.md` with relevant annotation guidelines used in the annotation project.

### Done when

- [x] The `README.md` is updated with relevant information.
- [x] The `guidelines.md` is updated with relevant information.

**Comment by jarumihooi** [comment]
closed by #41
