### ISSUE TITLE
Edit NEL process.py (orig:add README.md)

### ISSUE THREAD

**Issue by wricketts** [clamsproject/aapb-annotations#25]
### Because

The [2022 December NEL](https://github.com/clamsproject/aapb-annotations/tree/170115f37b9f67d49077e23ffc8ba237ba4e3092/newshour-namedentity-wikipedialink) project has an incomplete `README.md` file. As stated in the main [repository README](https://github.com/clamsproject/aapb-annotations/blob/main/README.md) file, we want each subdirectory to contain its own `README.md` detailing annotation project-specific information (e.g. project name, annotator demographics, annotation environment information, gold generation code dependencies, etc.). 

For this project in particular, the input was from the `newshour-namedentity` annotation project.

### Done when

- [x] The README.md is updated with relevant information.

### Additional context

 Issue https://github.com/clamsproject/aapb-annotations/issues/26 should probably be addressed first since it directly impacts this project.

**Comment by jarumihooi** [comment]
As of the completion of #60 and #63, this project only requires an update to the contents of and code for process.py plus an explanation.

**Comment by jarumihooi** [comment]
Ok, to clarfiy, this seems to be something you suggested in one of the edits.  
```
2 months ago

[some small edits](https://github.com/clamsproject/aapb-annotations/commit/c512dfbc61b41850d0b3d093b36b57ef50586d46)
_TODO: get rid og goldretriver and change the proc.py to alway read in local "raw" files_
```
